before_script:
  - npm install -g npm
  - npm install -g bower
  - bower install -f
language: node_js
node_js: 
    - "0.12.9"
script: node_modules/karma/bin/karma start ./tests/karma.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
